const translations = {
  en: {
    privacy: {
      title: "Privacy Policy",
      intro: "This policy explains how Bilgi OpenStackTool processes personal data when you use Bilgi NFC, create or manage digital cards, or visit a public card.",
      sections: [
        ["Data controller", <>Bilgi OpenStackTool is the service operator and data controller for the processing described here. For privacy requests or questions, contact <a href="mailto:contact@openstacktool.com">contact@openstacktool.com</a>.</>],
        ["Personal data we process", <ul><li><strong>Account and sign-in data:</strong> name, email address, optional phone number, account identifier, sign-in provider, verification status, and authentication/session data. Passwords are handled by Supabase Auth; the application does not receive or store a readable password.</li><li><strong>Card data:</strong> card title, IBAN and bank/account-holder details entered by the card owner, social and other links, contact information, access settings, and NFC-related settings.</li><li><strong>Feedback and support:</strong> messages, ratings, optional contact details, support requests, and abuse reports that users choose to submit.</li><li><strong>Device and access information:</strong> requests to the application and service providers may generate IP address, browser/device, timestamp, and security log data. Such information may be processed in provider logs; the application does not use it to build advertising profiles.</li><li><strong>Preferences and consent:</strong> language and theme settings, marketing preference, onboarding choice, and records of required confirmations.</li></ul>],
        ["Purposes", <>We use data to create and secure accounts; authenticate users; create, resolve, and display cards; enable user-requested feedback and support; prevent abuse and protect service availability; maintain and troubleshoot the service; meet legal obligations; and send product updates only when the user has opted in. Public card information is displayed to visitors according to the card owner's sharing settings.</>],
        ["Legal grounds", <>Depending on the purpose and applicable law, processing is based on providing the service requested by the user, compliance with legal obligations, legitimate interests such as service security where permitted, or consent where consent is required or selected (including optional marketing). Consent may be withdrawn at any time; withdrawal does not affect processing already carried out lawfully.</>],
        ["Service providers and recipients", <>The service uses Supabase for authentication and database services, Cloudflare for content delivery and edge/static hosting, and Google where a user chooses Google sign-in or follows a Google review link. Authentication email/SMS delivery may use providers configured for the Supabase project. Providers process information to provide their services and may have their own logs, subprocessors, and privacy terms.</>],
        ["Cookies, browser storage, and analytics", <>The dashboard uses browser storage for Supabase Auth session persistence and for language/theme preferences. Supabase session persistence in this application uses browser storage and should not be described as a cookie unless production settings actually configure cookies. No advertising tracker or behavioral analytics integration is configured in the checked-in application. Hosting and security providers may produce operational or aggregated telemetry; their exact data and retention are governed by the deployed provider settings.</>],
        ["Public cards and sharing", <>Information placed on a public card can be viewed by anyone who can reach its page. A private-card link acts as a bearer link: anyone who obtains it may be able to access that card. Please do not place sensitive information in a public card or share a private link with people who should not have access.</>],
        ["Retention and security", <>Account and card information is kept while needed to provide the service and while the account is active, subject to applicable legal obligations. An account deletion request can be submitted in account settings or by email. The application requests deletion of the account and related database records; copies in backups, operational logs, or third-party systems may remain for their documented retention period or where the law requires retention. Data is protected using the controls configured with the service providers, including encrypted connections; no online service can guarantee absolute security.</>],
        ["Your rights and choices", <>Subject to applicable law, you may request access to, correction of, export of, or deletion of your personal data, and may have additional rights such as restriction, objection, or portability. You can use account settings for available export and deletion functions or email <a href="mailto:contact@openstacktool.com">contact@openstacktool.com</a>. You may also withdraw optional marketing consent. We may ask for information needed to verify your identity.</>],
        ["Children and updates", <>The service is not intended for people below the minimum age applicable in their country. We may update this policy as the service or applicable requirements change and will publish the revised text on this page.</>],
      ],
    },
    notice: {
      title: "GDPR / KVKK Data Protection Notice",
      intro: "This notice describes personal-data processing by Bilgi OpenStackTool under the EU General Data Protection Regulation (GDPR) and Türkiye's Personal Data Protection Law No. 6698 (KVKK), where applicable.",
      sections: [
        ["Controller and contact", <>The controller for the processing described in this notice is Bilgi OpenStackTool. For data-subject requests, contact <a href="mailto:contact@openstacktool.com">contact@openstacktool.com</a>. If a card publisher independently determines the purposes and means of processing information published in a card, that publisher may also have controller responsibilities for that content.</>],
        ["Data categories and collection", <>Depending on features used, we process account and contact details; authentication identifiers and session data; card content such as IBAN, bank/account-holder details, social links and contact information; ratings and feedback; support and abuse reports; consent and preference records; and technical/security information generated by application and provider requests. Data is provided by account holders and visitors, by chosen identity providers, or generated when the service is used. Supabase Auth handles passwords; the application does not store passwords in readable form.</>],
        ["Purposes and legal bases", <>Purposes include account creation and authentication, card creation and public/private resolution, feedback and support, service security and abuse prevention, maintenance, and compliance with legal obligations. Where applicable, GDPR Article 6(1)(b) and KVKK Article 5(2)(c) may apply to processing necessary to provide the requested service or perform the user agreement. Consent under GDPR Article 6(1)(a) and explicit consent under KVKK Article 5(1) are relied on only for processing for which consent is the appropriate legal basis, including optional marketing or other consent-based processing. Other legal bases may apply where permitted; consent is not treated as the universal basis for all processing.</>],
        ["Recipients and international transfers", <>Data may be processed by Supabase (authentication/database), Cloudflare (content delivery and edge/static hosting), Google (user-selected OAuth and review destinations), and configured authentication message providers. Providers may process data in or transfer it to locations outside your country. Connections to the service use HTTPS where configured, and provider infrastructure may encrypt stored data according to its service configuration. The controller must ensure and document the transfer mechanism and safeguards required for the actual destinations and deployment; this notice does not assert that a particular certification or transfer arrangement applies.</>],
        ["Retention and deletion", <>Account and card data is generally retained while the account is active and the service is needed. You may request account deletion through account settings or by contacting us. The application is designed to delete the account and cascade deletion to related database records when the deletion request succeeds. Backup copies, provider logs, or records required for legal/security purposes may remain until their applicable retention period ends or deletion is legally permitted. Such residual retention is not an assertion of immediate deletion from every provider system.</>],
        ["Rights under the GDPR and KVKK", <>Where GDPR applies, Chapter III rights may include access, rectification, erasure, restriction, data portability, objection, and the right not to be subject to certain automated decisions, as applicable. Under KVKK Article 11, you may have the right to learn whether personal data is processed, request information, learn the purposes and recipients, request correction or deletion/destruction where conditions are met, request notification of such actions to recipients, object to certain outcomes, and seek compensation for unlawful processing. You may also complain to the competent supervisory authority or Turkish Personal Data Protection Authority, as applicable.</>],
        ["How to exercise your rights", <>Submit a request through account settings where available or email <a href="mailto:contact@openstacktool.com">contact@openstacktool.com</a>. Please identify the account and request clearly; we may need to verify your identity. We will respond within the period required by applicable law. You may withdraw consent at any time where processing is based on consent.</>],
        ["Security, children, and updates", <>We apply technical and organizational safeguards appropriate to the service, including access controls and encrypted connections where configured; no system can guarantee absolute security. The service is not intended for people below the applicable minimum age. This notice may be updated to reflect changes to processing or law.</>],
      ],
    },
  },
  tr: {
    privacy: {
      title: "Gizlilik Politikası",
      intro: "Bu politika, Bilgi NFC'yi kullandığınızda, dijital kart oluşturup yönettiğinizde veya herkese açık bir kartı ziyaret ettiğinizde Bilgi OpenStackTool'un kişisel verileri nasıl işlediğini açıklar.",
      sections: [
        ["Veri sorumlusu", <>Burada açıklanan işleme faaliyetleri bakımından hizmet işletmecisi ve veri sorumlusu Bilgi OpenStackTool'dur. Gizlilik talepleri ve sorularınız için <a href="mailto:contact@openstacktool.com">contact@openstacktool.com</a> adresine yazın.</>],
        ["İşlenen kişisel veriler", <ul><li><strong>Hesap ve giriş bilgileri:</strong> ad, e-posta adresi, isteğe bağlı telefon numarası, hesap tanımlayıcısı, giriş sağlayıcısı, doğrulama durumu ve kimlik doğrulama/oturum verileri. Parolalar Supabase Auth tarafından işlenir; uygulama okunabilir parola almaz veya saklamaz.</li><li><strong>Kart verileri:</strong> kart başlığı, kart sahibinin girdiği IBAN ve banka/hesap sahibi bilgileri, sosyal medya ve diğer bağlantılar, iletişim bilgileri, erişim ayarları ve NFC ile ilgili tercihler.</li><li><strong>Geri bildirim ve destek:</strong> kullanıcıların göndermeyi seçtiği mesajlar, puanlar, isteğe bağlı iletişim bilgileri, destek talepleri ve kötüye kullanım bildirimleri.</li><li><strong>Cihaz ve erişim bilgileri:</strong> uygulama ve hizmet sağlayıcılarına yapılan istekler IP adresi, tarayıcı/cihaz, zaman damgası ve güvenlik günlüğü verileri oluşturabilir. Bu bilgiler sağlayıcı günlüklerinde işlenebilir; uygulama bunları reklam profili oluşturmak için kullanmaz.</li><li><strong>Tercih ve onaylar:</strong> dil ve tema ayarları, pazarlama tercihi, hesap başlangıç tercihi ve zorunlu teyit kayıtları.</li></ul>],
        ["İşleme amaçları", <>Verileri hesap oluşturmak ve güvenliğini sağlamak; kullanıcıları doğrulamak; kart oluşturmak, çözümlemek ve görüntülemek; kullanıcının talep ettiği geri bildirim ve desteği sunmak; kötüye kullanımı önlemek ve hizmetin kullanılabilirliğini korumak; hizmeti sürdürmek ve sorun gidermek; hukuki yükümlülükleri yerine getirmek ve yalnızca kullanıcının tercih etmesi halinde ürün güncellemeleri göndermek için kullanırız. Herkese açık kart bilgileri, kart sahibinin paylaşım ayarlarına göre ziyaretçilere gösterilir.</>],
        ["Hukuki sebepler", <>İşleme amacı ve uygulanabilir hukuka bağlı olarak, kullanıcı tarafından talep edilen hizmetin sunulması, hukuki yükümlülük, izin verilen hallerde hizmet güvenliği gibi meşru menfaatler veya rıza gereken/seçilen işleme faaliyetleri (isteğe bağlı pazarlama dahil) hukuki sebep olabilir. Rıza her zaman geri alınabilir; geri alma, önceki hukuka uygun işlemeyi etkilemez.</>],
        ["Hizmet sağlayıcıları ve alıcılar", <>Hizmet; kimlik doğrulama ve veritabanı için Supabase, içerik dağıtımı ve edge/statik barındırma için Cloudflare kullanır. Kullanıcı Google ile giriş yapmayı seçtiğinde veya Google yorum bağlantısını açtığında Google hizmetleri kullanılır. Kimlik doğrulama e-posta/SMS iletimi Supabase projesinde yapılandırılan sağlayıcılardan yararlanabilir. Sağlayıcılar hizmet sunmak için verileri işler; kendi günlükleri, alt işleyenleri ve gizlilik koşulları olabilir.</>],
        ["Çerezler, tarayıcı depolaması ve analiz", <>Panel, Supabase Auth oturumunun sürdürülmesi ile dil/tema tercihlerinin saklanması için tarayıcı depolamasını kullanır. Bu uygulamada Supabase oturumu tarayıcı depolamasında tutulur; üretim ayarlarında çerez kullanılmıyorsa bu işlem çerez olarak tanımlanmamalıdır. Depoda reklam izleyicisi veya davranışsal analiz entegrasyonu yapılandırılmamıştır. Barındırma ve güvenlik sağlayıcıları operasyonel veya toplu telemetri oluşturabilir; kapsam ve saklama, canlı sağlayıcı ayarlarına bağlıdır.</>],
        ["Herkese açık kartlar ve paylaşım", <>Herkese açık karta eklenen bilgiler sayfaya ulaşabilen herkesçe görüntülenebilir. Özel kart bağlantısı erişim anahtarı gibi çalışır; bağlantıyı edinen kişiler karta erişebilir. Lütfen herkese açık karta hassas bilgi koymayın ve özel bağlantıyı erişmesini istemediğiniz kişilerle paylaşmayın.</>],
        ["Saklama ve güvenlik", <>Hesap ve kart bilgileri, hizmeti sunmak için gerekli olduğu ve hesap etkin olduğu sürece, uygulanabilir hukuki yükümlülükler saklı kalmak üzere tutulur. Hesap ayarlarından veya e-posta ile hesap silme talebi gönderebilirsiniz. Uygulama, hesabın ve ilişkili veritabanı kayıtlarının silinmesini talep eder; yedeklerdeki, operasyonel günlüklerdeki veya üçüncü taraf sistemlerindeki kopyalar belgelenmiş saklama süresince ya da kanunen gerektiğinde kalabilir. Hizmet sağlayıcılarında yapılandırılmış kontroller ve şifreli bağlantılar kullanılır; hiçbir çevrimiçi hizmet mutlak güvenlik garantisi veremez.</>],
        ["Haklarınız ve tercihleriniz", <>Uygulanabilir hukuka bağlı olarak kişisel verilerinize erişme, düzeltme, dışa aktarma veya silme talep etme; ayrıca kısıtlama, itiraz veya taşınabilirlik gibi haklara sahip olabilirsiniz. Kullanılabilir dışa aktarma ve silme özellikleri için hesap ayarlarını veya <a href="mailto:contact@openstacktool.com">contact@openstacktool.com</a> adresini kullanın. İsteğe bağlı pazarlama rızanızı da geri alabilirsiniz. Kimliğinizi doğrulamak için ek bilgi istenebilir.</>],
        ["Çocuklar ve güncellemeler", <>Hizmet, ülkenizde geçerli asgari yaşın altındaki kişiler için tasarlanmamıştır. Hizmet veya uygulanabilir gereklilikler değiştikçe bu politika güncellenebilir ve yeni metin bu sayfada yayımlanır.</>],
      ],
    },
    notice: {
      title: "GDPR / KVKK Veri Koruma Bilgilendirmesi",
      intro: "Bu bilgilendirme, uygulanabildiği ölçüde Bilgi OpenStackTool'un AB Genel Veri Koruma Tüzüğü (GDPR) ve 6698 sayılı Kişisel Verilerin Korunması Kanunu (KVKK) kapsamındaki kişisel veri işleme faaliyetlerini açıklar.",
      sections: [
        ["Veri sorumlusu ve iletişim", <>Bu bilgilendirmede açıklanan işlemler için veri sorumlusu Bilgi OpenStackTool'dur. İlgili kişi talepleri için <a href="mailto:contact@openstacktool.com">contact@openstacktool.com</a> adresine başvurun. Kartı yayımlayan kişi, kart içeriğindeki verilerin işlenme amaç ve araçlarını bağımsız belirliyorsa bu içerik bakımından ayrıca veri sorumluluğu üstlenebilir.</>],
        ["Veri kategorileri ve toplama", <>Kullanılan özelliklere bağlı olarak hesap ve iletişim bilgileri; kimlik doğrulama tanımlayıcıları ve oturum verileri; IBAN, banka/hesap sahibi bilgileri, sosyal bağlantılar ve iletişim bilgileri gibi kart içeriği; puan ve geri bildirimler; destek ve kötüye kullanım bildirimleri; onay ve tercih kayıtları; uygulama ve sağlayıcı isteklerinden üretilen teknik/güvenlik bilgileri işlenebilir. Veriler hesap sahipleri ve ziyaretçilerden, tercih edilen kimlik sağlayıcılarından veya hizmet kullanımı sırasında elde edilir. Parolalar Supabase Auth tarafından işlenir; uygulama parolaları okunabilir biçimde saklamaz.</>],
        ["Amaçlar ve hukuki sebepler", <>Amaçlar hesap açma ve kimlik doğrulama, kart oluşturma ve herkese açık/özel kartı çözümleme, geri bildirim ve destek, hizmet güvenliği ve kötüye kullanımı önleme, bakım ve hukuki yükümlülüklere uyumu kapsar. Uygulanabildiği ölçüde, talep edilen hizmetin sunulması veya kullanıcı sözleşmesinin ifası için gerekli işlemlerde GDPR m. 6(1)(b) ve KVKK m. 5(2)(c) uygulanabilir. GDPR m. 6(1)(a) kapsamındaki rıza ve KVKK m. 5(1) kapsamındaki açık rıza, yalnızca rızanın uygun hukuki sebep olduğu işlemlerde (isteğe bağlı pazarlama veya rızaya dayalı diğer işlemler gibi) kullanılır. İzin verilen hallerde başka hukuki sebepler uygulanabilir; rıza tüm işlemlerin genel sebebi değildir.</>],
        ["Alıcılar ve yurt dışına aktarım", <>Veriler Supabase (kimlik doğrulama/veritabanı), Cloudflare (içerik dağıtımı ve edge/statik barındırma), Google (kullanıcının seçtiği OAuth ve yorum hedefleri) ve yapılandırılmış kimlik doğrulama ileti sağlayıcıları tarafından işlenebilir. Sağlayıcılar verileri ülkeniz dışındaki konumlarda işleyebilir veya bu konumlara aktarabilir. Yapılandırıldığı ölçüde hizmet bağlantıları HTTPS kullanır ve sağlayıcı altyapısı kendi hizmet ayarlarına göre depolanan verileri şifreleyebilir. Veri sorumlusu, gerçek hedefler ve dağıtım için gereken aktarım mekanizması ve güvenceleri belirlemeli ve belgelemelidir; bu metin belirli bir sertifika veya aktarım düzenlemesinin geçerli olduğunu ileri sürmez.</>],
        ["Saklama ve silme", <>Hesap ve kart verileri genel olarak hesap etkin olduğu ve hizmete ihtiyaç duyulduğu sürece saklanır. Hesap ayarlarından veya bize ulaşarak silme talebinde bulunabilirsiniz. Silme talebi başarıyla tamamlandığında uygulama, hesabı ve ilişkili veritabanı kayıtlarını zincirleme silmek üzere tasarlanmıştır. Yedek kopyalar, sağlayıcı günlükleri veya hukuki/güvenlik amaçlarıyla gerekli kayıtlar, geçerli saklama süresi bitene ya da silmeye hukuken izin verilene kadar kalabilir. Bu durum, tüm sağlayıcı sistemlerinden derhal silme garantisi değildir.</>],
        ["GDPR ve KVKK kapsamındaki haklar", <>GDPR uygulanıyorsa III. Bölüm kapsamındaki haklar; erişim, düzeltme, silme, işlemenin kısıtlanması, veri taşınabilirliği, itiraz ve uygulanabilir olduğu hallerde belirli otomatik kararlar karşısında hakları içerebilir. KVKK m. 11 kapsamında kişisel verilerin işlenip işlenmediğini öğrenme, bilgi talep etme, amaçları ve alıcıları öğrenme, şartları varsa düzeltme veya silme/yok etme isteme, bu işlemlerin alıcılara bildirilmesini isteme, belirli sonuçlara itiraz etme ve hukuka aykırı işleme nedeniyle zararın giderilmesini talep etme haklarınız olabilir. Ayrıca uygulanabilir olduğu ölçüde yetkili denetim makamına veya Kişisel Verileri Koruma Kurumuna şikâyette bulunabilirsiniz.</>],
        ["Hakların kullanılması", <>Kullanılabildiği ölçüde hesap ayarlarından veya <a href="mailto:contact@openstacktool.com">contact@openstacktool.com</a> adresinden başvurun. Lütfen ilgili hesabı ve talebinizi açıkça belirtin; kimliğinizi doğrulamamız gerekebilir. Başvurular uygulanabilir mevzuattaki süre içinde yanıtlanır. İşleme rızaya dayanıyorsa rızanızı istediğiniz zaman geri alabilirsiniz.</>],
        ["Güvenlik, çocuklar ve güncellemeler", <>Yapılandırıldığı ölçüde erişim kontrolleri ve şifreli bağlantılar dahil uygun teknik/idari tedbirler uygulanır; hiçbir sistem mutlak güvenlik sağlayamaz. Hizmet, geçerli asgari yaşın altındaki kişiler için tasarlanmamıştır. İşleme faaliyetleri veya mevzuat değiştiğinde bu bilgilendirme güncellenebilir.</>],
      ],
    },
  },
};

const routes = {
  en: {
    privacy: "/en/privacy-policy",
    notice: "/en/gdpr",
  },
  tr: {
    privacy: "/tr/gizlilik-politikasi",
    notice: "/tr/kvkk",
  },
};

export function LegalDocumentPage({ document, language }) {
  const lang = language === "tr" ? "tr" : "en";
  const content = translations[lang][document] || translations[lang].privacy;
  const otherLanguage = lang === "tr" ? "en" : "tr";

  return (
    <main className="legal-page">
      <header className="legal-page-header">
        <a className="brand" href="/">bilgi</a>
        <a className="legal-language-link" href={routes[otherLanguage][document]}>
          {otherLanguage === "tr" ? "Türkçe" : "English"}
        </a>
      </header>
      <article className="legal-document">
        <p className="eyebrow">{lang === "tr" ? "Bilgi · Yasal bilgilendirme" : "Bilgi · Legal information"}</p>
        <h1>{content.title}</h1>
        <p className="legal-intro">{content.intro}</p>
        {content.sections.map(([heading, body]) => (
          <section key={heading}>
            <h2>{heading}</h2>
            {body}
          </section>
        ))}
        <footer className="legal-page-footer">
          <a href={routes[lang].privacy}>{lang === "tr" ? "Gizlilik Politikası" : "Privacy Policy"}</a>
          <a href={routes[lang].notice}>{lang === "tr" ? "KVKK / GDPR Bilgilendirmesi" : "GDPR / KVKK Notice"}</a>
          <a href={routes[otherLanguage][document]}>{lang === "tr" ? "English" : "Türkçe"}</a>
        </footer>
      </article>
    </main>
  );
}
